### ISSUE TITLE
HTTPS support for Docker image

### ISSUE THREAD

**Issue by Donnerbart** [postmanlabs/httpbin#515]
I'm trying to dockerize our HTTP integration tests, which use `httpbin.org` a lot. The docker image `kennethreitz/httpbin` works like a charm, but not for HTTPS connections.

The configuration
```
  @ClassRule
  public static final GenericContainer HTTPBIN = new GenericContainer("kennethreitz/httpbin:latest")
      .withExposedPorts(80);
```
fails with a startup error. And using `https` against port 80 results in
```
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1002)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:267)
```
etc.

Is there any chance to get this running with the provided docker image? Any other solutions or ideas?

**Comment by avishayp** [comment]
This could be handled by a proxy of some sort. As example, adding this to your `docker-compose.yml`:

```
    proxy:
      image: lordius/alpine-ngrok
      ports:
        - 4040:4040
      entrypoint: ngrok http httpbin:80
      links:
        - httpbin
```

then `curl -s localhost:4040/api/tunnels/ | jq -r '.tunnels[1].public_url'` will give you the (public, temporary) ngrok tunnel url. Hope that helps. If the setup has to be local, use a local proxy (nginx+letsencrypt).

**Comment by javabrett** [comment]
I'm thinking you are going to generate an untrusted, self-signed certificate here on-the-fly?

You could derive a sub Dockerfile and run commands such as:

`openssl req -x509 -newkey rsa:4096 -nodes -out /etc/ssl/certs/cert.pem -keyout /etc/ssl/private/key.pem -days 365 -subj "CN=www.example.com"`

`gunicorn -b 0.0.0.0:443 httpbin:app -k gevent --certfile /etc/ssl/certs/cert.pem --keyfile /etc/ssl/private/key.pem`

**Comment by avishayp** [comment]
Example:

```yaml
version: '2'

services:

    httpbin:
      image: kennethreitz/httpbin

    proxy:
      image: fsouza/docker-ssl-proxy
      environment:
        DOMAIN: localhost
        TARGET_HOST: httpbin
      links:
        - httpbin
      ports:
        - 443:443
```

```bash
$ curl --insecure https://localhost/ip
{
  "origin": "192.168.48.1"
}
```
